154 prototype external dataset storage
hydraplatform/hydra-base pull request #158
Opened 2022-06-13 12:32 UTC by pmslavin

Adds external storage of "large" datasets to a MongoDB instance.

* "Large" datasets are those exceeding a threshold defined in config
* Datasets are transparently migrated to and from external storage as their size requires
* Bulk insert routines updated to handle external storage
* New mongo-specific tests added and existing tests extended
* Utility module added to identify and migrate existing datasets

2022-06-28 09:05 UTC, knoxsp requested changes
It also looks like 'pylibmc' is missing from install_requires.
Perhaps we should install using requirement.txt instead so there's only one list of dependencies?

2022-06-30 15:45 UTC, pmslavin commented on hydra_base/db/model.py
> +    value_ref  = Column('value', Text().with_variant(mysql.LONGTEXT, 'mysql'),  nullable=True)
Don't think so, the db column is unchanged although the class attr has a new name.

2022-06-30 15:47 UTC, pmslavin commented on hydra_base/lib/adaptors.py
> +class DatasetAdaptor(ABC):
This has been reorganised in the latest commits.  Is now a Mongo-specific `MongoDatasetAdapter` in a new package `lib.storage`.

2022-06-30 16:04 UTC, pmslavin commented on hydra_base/lib/datasetmanager.py
> +            cols = get_session().execute(qry_txt).one()
Original reason was to test performance and avoid having to import `Metadata` from model.py into the function, but the two text-based queries have been removed as they were unused.

2022-06-30 16:05 UTC, pmslavin commented on hydra_base/lib/datasetmanager.py
> +        qry_txt = f"delete from tMetadata where dataset_id = {dataset_id} and `key` = '{self.loc_key}'"
Removed with the other text-based query.

2022-06-30 16:05 UTC, pmslavin commented on hydra_base/lib/objects.py
> +            if ref_key:
Changed.

2022-06-30 16:06 UTC, pmslavin commented on hydra_base/lib/objects.py
> +def get_external_value_by_object_id(oid):
I've removed this whole function and changed the logic in `JSONObject` above in recent commits.

A normal method in the adapter is now called to get the document.

2022-06-30 16:07 UTC, pmslavin commented on hydra_base/util/storage.py
> +    collection = collection if collection else mongo_config["datasets"]
The default argument was a mistake from testing which should have been removed.

The default is now `None` so this selects between either an optional arg or the config default.

2022-06-30 16:07 UTC, pmslavin commented on hydra_base/lib/adaptors.py
> +    def get_document_by_object_id(self, object_id, collection=None):
Added.

2022-06-30 16:47 UTC, pmslavin commented
This has several changes:
* Adaptor => Adapter as this seems more usual
* External storage-related classes refactored into a `storage` package
*  Adapter does not derive from an abstract base class: because there's adapter-specific behaviour in a `DatasetManager` class that uses it, there's no point having adapters conform to a consistent interface when each manager uses only one adapter
*  `DatasetManager` *does* derive from an abstract base class as this is the entity that changes to swap in a different external storage source, ie we need only set `Dataset.value = SomeDatasetManager()` in `model.py` to swap. This class provides the expected descriptor methods and others which manage the storage location metadata
* A few isolated functions are now included in the adapter class
* CI workflow has been added. It seems the runner Ubuntu image includes (the official -org version of) the MongoDB package, so it is only necessary to start this
*  Fixes and clarifications as per comments
 
There's no mention of `pylibmc` in `install_requires` as there's no caching yet in this branch.  It does now include `pymongo` and the CI workflow succeeds with this.

2022-07-26 09:32 UTC, knoxsp commented on hydra_base/lib/data.py
> +    if mongo_data:
```suggestion
    if mongo_data is not None:
```

2022-07-26 09:45 UTC, knoxsp approved these changes

2022-07-26 09:46 UTC, knoxsp approved these changes

2022-07-26 10:01 UTC, merged